# Example configuration for Free BDR Pipeline
linkedin:
  lists:
    new_leads: https://www.linkedin.com/sales/lists/people/NEW_LIST_ID
    invited: https://www.linkedin.com/sales/lists/people/INVITED_LIST_ID
    connected: https://www.linkedin.com/sales/lists/people/CONNECTED_LIST_ID
  # Username and password are only required for automated headless runs.
  # They can be omitted when logging in manually via the dashboard.
  username: "your_email@example.com"
  password: "YOUR_LINKEDIN_PASSWORD"
  searches:
    - name: "Example Search"
      url: "https://www.linkedin.com/sales/search/people?..."
hubspot:
  api_key: "YOUR_HUBSPOT_API_KEY"
huggingface:
  token: "YOUR_HF_TOKEN"
  model: "meta-llama/Llama-2-7b-chat-hf"
rate_limits:
  min_delay_sec: 30
  max_delay_sec: 90
seeds:
  connection: "Hi {{FirstName}}, I noticed…"
  followup: "Hello {{FirstName}}, just checking…"
gsheets:
  creds_json: "path/to/google-creds.json"
  spreadsheet_id: "GOOGLE_SHEET_ID"
  leads_ws: "Leads"
  report_ws: "Report"
  metadata_ws: "Metadata"
