# Copy this template and fill in your details
linkedin:
  # Username and password are only needed when running modules headlessly.
  # Leave them blank if you log in manually via the dashboard.
  username: "your_email@example.com"
  password: "YOUR_LINKEDIN_PASSWORD"
  searches:
    - name: "FinTech CIOs Canada"
      url: "https://www.linkedin.com/sales/search/people?..."
hubspot:
  api_key: "YOUR_HUBSPOT_API_KEY"
huggingface:
  token: "YOUR_HUGGINGFACE_TOKEN"
  model: "meta-llama/Llama-2-7b-chat-hf"
rate_limits:
  min_delay_sec: 30
  max_delay_sec: 90
seeds:
  connection: "Hi {{FirstName}}, I noticed…"
  followup:   "Hello {{FirstName}}, just checking…"
gsheets:
  creds_json: "path/to/google-creds.json"
  spreadsheet_id: "GOOGLE_SHEET_ID"
  leads_ws: "Leads"
  report_ws: "Report"
  metadata_ws: "Metadata"
