gsheets:
  creds_json: /Users/infoobjects/Tools/Test/datafiles/focus-invention-251008-53ba8c8d891e.json
  leads_ws: Leads
  report_ws: Report
  metadata_ws: Report
  spreadsheet_id: 1CZh1XEXKuqyZYkOAfgMtVvNYzcvv_7zY84z1N6oueIQ
hubspot:
  api_key: YOUR_HUBSPOT_API_KEY
huggingface:
  model: meta-llama/Llama-2-7b-chat-hf
  token: YOUR_HUGGINGFACE_TOKEN
linkedin:
  password: ''
  searches:
  - name: Recommended Leads
    url: https://www.linkedin.com/sales/lists/people/6959228537564233728?sortCriteria=LAST_ACTIVITY&sortOrder=DESCENDING
  username: your_email@example.com
rate_limits:
  max_delay_sec: 90
  min_delay_sec: 30
seeds:
  connection: "Hi {{FirstName}}, I noticed\u2026"
  followup: "Hello {{FirstName}}, just checking\u2026"
